name: "Basic Tests"

on:
  pull_request:
    types:
      - 'synchronize'
      - 'opened'

jobs:
  setup:
    uses: ./.github/workflows/reusable_setup.yml
    secrets:
      CAP_GH_RELEASE_TOKEN: ${{ secrets.CAP_GH_RELEASE_TOKEN }}

  lint-test:
    needs: 'setup'
    uses: ./.github/workflows/reusable_lint-packages.yml
    secrets:
      CAP_GH_RELEASE_TOKEN: ${{ secrets.CAP_GH_RELEASE_TOKEN }}

  verify-packages:
    needs: 'setup'
    uses: ./.github/workflows/reusable_verify-packages.yml
    secrets:
      CAP_GH_RELEASE_TOKEN: ${{ secrets.CAP_GH_RELEASE_TOKEN }}
